version: "3.9"

services:
  postgres:
    image: postgres:13.3
    container_name: postgres
    restart: unless-stopped
    hostname: postgres
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    networks:
      - server-network
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data
  
  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    restart: unless-stopped
    hostname: mariadb
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "true"
    networks:
      - server-network
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - 3306:3306
    volumes:
      - ./mariadb_data:/var/lib/mysql

  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: unless-stopped
    hostname: redis
    networks:
      - server-network
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - 6379:6379

networks:
  server-network:
    external: true
