version: "3.9"

services:
  nginx:
    image: nginx:1.18.0-alpine
    container_name: nginx
    restart: unless-stopped
    hostname: nginx
    networks:
      server-network:
        aliases:
          - energetic.local
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - ./config:/etc/nginx
      - ~/Projects:/projects
      - ./certs/certs:/etc/ssl/certs/selfsigned
      - ./certs/private:/etc/ssl/private/selfsigned

networks:
  server-network:
    external: true
