version: "3.9"

services:
  *:
    image: php-nginx:7.4
    container_name: *
    hostname: *
    environment:
      PHP_IDE_CONFIG: serverName=*
      DB_HOST: mariadb
      REDIS_HOST: redis
    networks:
      - server-network
    volumes:
      - .:/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    working_dir: /app

networks:
  server-network:
    external: true
