version: "3.9"

services:
  *:
    image: php-nginx:7.4
    container_name: *
    hostname: *
    environment:
      PHP_IDE_CONFIG: serverName=*
      DB_HOST: host.docker.internal
      REDIS_HOST: *-redis
    networks:
      - server-network
    volumes:
      - .:/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    working_dir: /app

#   *-redis:
#     image: redis:6.2-alpine
#     container_name: *-redis
#     hostname: *-redis
#     networks:
#       - server-network
#     ports:
#       - 6379:6379 # Для использования artisan извне контейнера

networks:
  server-network:
    external: true
